FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install core build tools and cmake
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  clangd

EXPOSE 8080

WORKDIR ${PWD}
